version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
     interval: monthly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: flake8
    versions:
    - "> 3.7.9"
  - dependency-name: isort
    versions:
    - "> 5.6.4"
  - dependency-name: mypy
    versions:
    - "> 0.812"
