---
pull_request_rules:
  - name: default
    actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=continuous-integration/travis-ci/pr
      - status-success=ci/jenkins/pr_cloud_croud
      - status-success=Code style checks and static analysis with Python 3.8
      - status-success=Tests with Python 3.6
      - status-success=Tests with Python 3.7
      - status-success=Tests with Python 3.8
