language: python
cache: pip
matrix:
  include:
    - name: "Python 3.6"
      python: 3.6
      dist: trusty
    - name: "Python 3.7"
      python: 3.7
      dist: xenial  # required for python >= 3.7
sudo:
  false
install:
  - pip install -e .
  - pip install -r test-requirements.txt
  - pip install pytest-cov
script:
  - pytest --cov croud -vvv
after_success:
  - pip install coveralls
  - coveralls
notifications:
  email: false
