notifications:
  email: false

code: &code
  stage: "Code"
  dist: xenial
  language: python
  cache: pip
  sudo:
    false
  install:
    - pip install -e .
    - pip install -r test-requirements.txt
    - pip install pytest-cov
  script:
    - pytest --cov croud -vvv
  after_success:
    - pip install coveralls codecov
    - coveralls
    - codecov

docs: &docs
  stage: "Documentation"
  language: generic
  script:
    - cd docs && make check

matrix:
  include:

    - <<: *code
      name: "Python 3.6"
      python: 3.6
    - <<: *code
      name: "Python 3.7"
      python: 3.7

    - <<: *docs
      name: "Python 3.7"
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7-dev
            - python3.7-venv
    - <<: *docs
      name: "Python 3.7"
      os: osx
      osx_image: xcode10.2

