notifications:
  email: false

docs: &docs
  stage: "Documentation"
  language: generic
  script:
    - cd docs && make check

matrix:
  include:
    - <<: *docs
      name: "Python 3.7"
      dist: xenial
      addons:
        apt:
          sources:
            - deadsnakes
          packages:
            - python3.7-dev
            - python3.7-venv
    - <<: *docs
      name: "Python 3.7"
      os: osx
      osx_image: xcode10.2
